--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/cosmicnebula200/SellMe
build-by-default: true
branches:
- main
projects:
  SellMe:
    path: ""
    icon: 'sell.png'
    lint:
      phpstan: false
    libs:
      - src: Paroxity/CortexPE/Commando/Commando
        version:  ^3.1.0
        branch: PM4
      - src: muqsit/simplepackethandler/SimplePacketHandler
        version: ^0.1.3
        branch: pm5
      - src: Vecnavium/FormsUI/FormsUI
        version: ^1.1.3
...
